/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Server */

#ifndef _Included_Server
#define _Included_Server
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Server
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Server_sayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
