/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ServerImplements */

#ifndef _Included_ServerImplements
#define _Included_ServerImplements
#ifdef __cplusplus
extern "C" {
#endif
#undef ServerImplements_serialVersionUID
#define ServerImplements_serialVersionUID -3215090123894869218LL
#undef ServerImplements_serialVersionUID
#define ServerImplements_serialVersionUID -4100238210092549637LL
#undef ServerImplements_serialVersionUID
#define ServerImplements_serialVersionUID 4974527148936298033LL
/*
 * Class:     ServerImplements
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ServerImplements_sayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
